### ISSUE TITLE
Criação de máscaras em inputs

### ISSUE THREAD

**Issue by viniciosarodrigues** [viniciosarodrigues/gestao-de-prontuario-ui#7]
Atualmente, inputs como os de telefone, documentos, e cep não possuem máscaras. Esta atividade consiste na criação de máscaras para as telas abaixo:

- 1 - Formulário de Pacientes (Menu - Pacientes)
![image](https://user-images.githubusercontent.com/7918549/72228744-245b2980-3588-11ea-82b4-11e43dff8586.png)
- 2 Tela de prontuário (Menu - Prontuário)
![image](https://user-images.githubusercontent.com/7918549/72228791-7d2ac200-3588-11ea-895a-82d163154820.png)
- 3 - Tela de perfil pessoal (Menu - Perfil)
![image](https://user-images.githubusercontent.com/7918549/72228806-bbc07c80-3588-11ea-9674-1d276eb14e28.png)

**Comment by JairRibeiro** [comment]
Foram criadas as máscaras
